In [67]:
import requests
import pandas as pd
import cv2
import urllib.request
import numpy as np
from matplotlib import pyplot as plt
#from keras.preprocessing import image

%matplotlib inline


%store -r WORKDIR

#if 'WORKDIR' not in dir():
WORKDIR = 'C:/Users/cammy/OneDrive/MIT IA/git/projeto_dogs/dogs_brand'



baseurl = 'https://dog.ceo/api/'

listurl = baseurl + 'breeds/list/all'
randomappend = '/images/random/'
allimages = '/images'

data_raw_file = WORKDIR + '/Data/Raw/dogs.parquet'

maxBreeds = 5
maxImages = 50

img_h, img_w = 64, 64 # Altura e largura das imagens

#breeds = []

In [68]:
WORKDIR

'C:/Users/cammy/OneDrive/MIT IA/git/projeto_dogs/dogs_brand'

# Busca Lista de Raças

In [69]:
obj = requests.get(listurl).json()
allbreeds = pd.DataFrame.from_dict(obj)
allbreeds.head()

message   status
affenpinscher      []  success
african            []  success
airedale           []  success
akita              []  success
appenzeller        []  success

In [70]:
breeds = allbreeds.index
if maxBreeds > 0:
    breeds = allbreeds [0:maxBreeds].index
    

# Ler imagens

In [71]:
def ler_imagem(url):

# For remote, use urllib, as per "http://stackoverflow.com/questions/21061814"
    req = urllib.request.urlopen(url)

    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
# 0 = monocromatic
    img = cv2.imdecode(arr,0)
    imres = cv2.resize(img, (img_h, img_w), interpolation=cv2.INTER_CUBIC)


# Plot
#    plt.figure()  
#    plt.imshow(imres)
    return imres

In [72]:
imageurls = []
dogimages = []
rotulos = []
#dataset = np.ndarray((len(breeds) * maxImages, img_h, img_w, 3), dtype=np.uint8)
i = 0

for breed in breeds:
#    filesurl = baseurl + 'breed/' + breed + randomappend + str(maxImages)
    filesurl = baseurl + 'breed/' + breed + allimages
    imageurl = requests.get(filesurl).json()
    print(imageurl)
    breedimages = pd.DataFrame.from_dict(imageurl['message'])
    imageurls.append(breedimages)
    for images in breedimages.values:
        img = ler_imagem(images[0])
#        dataset[i] = img
        rotulos.append(breed)
        dogimages.append(img.flatten())
        i = i+1

{'message': ['https://images.dog.ceo/breeds/affenpinscher/n02110627_10147.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10185.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10225.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10437.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10439.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10447.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10680.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10787.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10848.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10859.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_10986.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_11211.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_11262.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n02110627_11263.jpg', 'https://images.dog.ceo/breeds/affenpinscher/n021

In [73]:
rotulos

['affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpinscher',
 'affenpin

In [74]:
#dataset.shape

In [75]:
dogimages

[array([ 42,  41, 127, ..., 105, 128, 120], dtype=uint8),
 array([ 78,  77,  78, ..., 115, 113, 109], dtype=uint8),
 array([178, 127,  73, ...,  58,  65,  91], dtype=uint8),
 array([183, 184, 186, ..., 178, 161, 156], dtype=uint8),
 array([128, 143, 174, ...,  38,  42,  41], dtype=uint8),
 array([110, 113, 115, ...,  49,  54,  57], dtype=uint8),
 array([255, 255, 255, ..., 254, 255, 254], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([ 15, 218, 163, ..., 210, 199, 207], dtype=uint8),
 array([ 25,  13, 157, ...,  61,  51,  48], dtype=uint8),
 array([105, 107,  73, ..., 187, 143, 164], dtype=uint8),
 array([125, 125, 137, ..., 110, 121,  78], dtype=uint8),
 array([ 7,  8,  8, ..., 30, 11, 10], dtype=uint8),
 array([55, 57, 63, ..., 72, 50, 52], dtype=uint8),
 array([192, 187, 184, ..., 105, 143, 147], dtype=uint8),
 array([ 95, 118,  80, ..., 108, 123, 151], dtype=uint8),
 array([ 47,  54,  60, ..., 131, 130, 128], dtype=uint8),
 array([ 49,  25,  25, ...

In [76]:
# view an image (e.g. 20) and print its corresponding label
#img_index = 10
#plt.imshow(dataset[img_index,:,:,:])
#plt.show()
#print(rotulos[img_index])

In [77]:
df = pd.DataFrame(dogimages)
df['breed'] = rotulos

In [78]:
df

0    1    2    3    4    5    6    7   8    9  ...  4087  4088  4089  \
0     42   41  127  125   49  111   98   16  54  178  ...    99    93    97   
1     78   77   78   78  106   68   81   64  69   67  ...   114   119   112   
2    178  127   73  184   85  108   99  109  39  153  ...    69    85   104   
3    183  184  186  186  189  191  200   78  86  157  ...   178   180   160   
4    128  143  174  253  253  253   43    7  12   15  ...    50    60    47   
..   ...  ...  ...  ...  ...  ...  ...  ...  ..  ...  ...   ...   ...   ...   
516   26   24   29   28   30   31   32   32  29   24  ...    51    51    50   
517   63   71   59   71   64   37  108   61  27   51  ...    91    65    75   
518  106  115  160  136   93   92  108   83  78   75  ...   135   111   140   
519   69   68   69   67   66   65   57   87  80   74  ...   181   172   150   
520   19   17   17   17   17   17   17   20  24   25  ...    36    32    30   

     4090  4091  4092  4093  4094  4095          breed  
0      92   102    97   105   128   120  affenpinscher  
1     105   105    87   115   113   109  affenpinscher  
2      64    95    69    58    65    91  affenpinscher  
3     162   140   154   178   161   156  affenpinscher  
4      48    50    39    38    42    41  affenpinscher  
..    ...   ...   ...   ...   ...   ...            ...  
516    48    59    56    54    45    49       airedale  
517   105    65    63    65    45    58       airedale  
518   150   102   127   154   128   134       airedale  
519   144   169   141   147   129    76       airedale  
520    29    29    29    28    26    19       airedale  

[521 rows x 4097 columns]

In [79]:
df.columns = df.columns.astype(str)
df.to_parquet(data_raw_file)